command-messages:
  restarts:
    restarting: "Restarting..."
    # Used for daily restarts.
    daily-minutes: "Daily restart in {TIME} minutes..."
    daily-minute: "Daily restart in {TIME} minute..."
    daily-seconds: "Daily restart in {TIME} seconds..."
    daily-second: "Daily restart in {TIME} second..."
    # Used for quick restarts.
    quick-minutes: "Quick restart in {TIME} minutes..."
    quick-minute: "Quick restart in {TIME} minute..."
    quick-seconds: "Quick restart in {TIME} seconds..."
    quick-second: "Quick restart in {TIME} second..."
    # Used for maintenance.
    maintenance-minutes: "Maintenance in {TIME} minutes..."
    maintenance-minute: "Maintenance in {TIME} minute..."
    maintenance-seconds: "Maintenance in {TIME} seconds..."
    maintenance-second: "Maintenance in {TIME} second..."

join-message:
  first: "&6{PLAYER}&3 has joined the server for the first time! (#%server_unique_joins%)"
  normal: "&6{PLAYER}&3 has joined the server."
  private: "&6You find yourself in a strange area. What now?"

leave-message: "&6{PLAYER}&3 has left the server."

ping-you: "&6Your ping is %player_ping_{PLAYER}%ms."
ping-other: "&6{PLAYER}'s ping is %player_ping_{PLAYER}%ms."

player-not-found: "&cThat player was not found."

uptime: "&6Server has been online for %server_uptime%."

speed:
  elytra:
    max-speed-overworld: 2.5
    max-speed-nether: 1.2
  normal:
    max-speed-overworld: 1.2
    max-speed-nether: 0.7
  entity:
    overworld: 1.5
    nether: 0.9

auto-messages:
  - "Want to talk to the homies privately? Use /party!"
  - "This is an automated message, don't worry!"
  - "Post some cool stuff on the subreddit: /r/DestroyMC"
  - "Use /help for all commands."
  - "Have a suggestion or found a bug? Report it at https://github.com/DESTROYMCNET/Feedback"
  - "Make to vote for the server on voting sites! Do /vote!"